language: node_js
node_js:
  - lts/*
install: npm ci
script: npm run build
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run semantic-release
